import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'astro/config';
import compress from 'astro-compress';
import rehypeExternalLinks from 'rehype-external-links';
import site from './src/data/site.json';

export default defineConfig({
  site: site.siteUrl,
  markdown: {
    rehypePlugins: [[rehypeExternalLinks, { target: '_blank', rel: ['noopener', 'noreferrer'] }]],
  },
  integrations: [
    sitemap({
      filter: (page) => !/\/(watch|projects)\/\d+\/?$/.test(page),
    }),
    mdx(),
    // CSS: false — astro-compress runs Lightning CSS as a second pass after Vite's own CSS
    // build, and that second pass strips @media range-syntax blocks (e.g. `width>=40rem`)
    // generated by Astro's scoped <style> processor, breaking responsive component styles.
    // Vite already minifies CSS during the build, so this pass adds no value.
    compress({
      CSS: false,
      Logger: 2,
      Action: {
        Accomplished: async ({
          Input,
          Before,
          After,
        }: {
          Input: string;
          Before: number;
          After: number;
        }) => {
          const path = Input.split('/dist').pop() ?? Input;
          const saved = Before - After;
          const pct = Before > 0 ? Math.round((saved / Before) * 100) : 0;
          return `  ${path}: ${Before}B → ${After}B (-${pct}%)`;
        },
      },
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});
